version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    networks:
      - infokes
    restart: always 

networks:
  infokes:
    external: true
